package com.bjpowernode.springboot.model;

public class Salary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALGRADE.GRADE
     *
     * @mbggenerated Thu Jul 07 11:12:01 CST 2022
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALGRADE.LOSAL
     *
     * @mbggenerated Thu Jul 07 11:12:01 CST 2022
     */
    private Integer losal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALGRADE.HISAL
     *
     * @mbggenerated Thu Jul 07 11:12:01 CST 2022
     */
    private Integer hisal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALGRADE.GRADE
     *
     * @return the value of SALGRADE.GRADE
     *
     * @mbggenerated Thu Jul 07 11:12:01 CST 2022
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALGRADE.GRADE
     *
     * @param grade the value for SALGRADE.GRADE
     *
     * @mbggenerated Thu Jul 07 11:12:01 CST 2022
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALGRADE.LOSAL
     *
     * @return the value of SALGRADE.LOSAL
     *
     * @mbggenerated Thu Jul 07 11:12:01 CST 2022
     */
    public Integer getLosal() {
        return losal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALGRADE.LOSAL
     *
     * @param losal the value for SALGRADE.LOSAL
     *
     * @mbggenerated Thu Jul 07 11:12:01 CST 2022
     */
    public void setLosal(Integer losal) {
        this.losal = losal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALGRADE.HISAL
     *
     * @return the value of SALGRADE.HISAL
     *
     * @mbggenerated Thu Jul 07 11:12:01 CST 2022
     */
    public Integer getHisal() {
        return hisal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALGRADE.HISAL
     *
     * @param hisal the value for SALGRADE.HISAL
     *
     * @mbggenerated Thu Jul 07 11:12:01 CST 2022
     */
    public void setHisal(Integer hisal) {
        this.hisal = hisal;
    }
}